# Generated by Django 2.2.12 on 2020-05-05 11:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shortcode', models.CharField(help_text='url shortname', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid shortcode', message='shortcode must be lowercase alpha numeric charater; underscore is allowed.', regex='^[a-z0-9_]{6}')], verbose_name='shorcode')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('_redirect_count', models.IntegerField(default=0, help_text='Number of times shortcode has been retreived')),
                ('last_redirect', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='redirect_count')),
            ],
            options={
                'ordering': ('created', 'modified'),
            },
        ),
    ]
