# Generated by Django 2.2.12 on 2020-05-03 12:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=100, unique=True)),
                ('redirect_count', models.IntegerField()),
                ('last_redirect', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='redirect_count')),
            ],
            options={
                'ordering': ('created', 'modified'),
            },
        ),
    ]
