# Generated by Django 2.2.12 on 2020-05-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
