# Generated by Django 2.2.12 on 2020-05-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20200503_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='redirect_count',
            new_name='_redirect_count',
        ),
    ]
